import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :agento, AgentoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Agento serves plain HTTP on the local network. There is no `force_ssl`
# here: nothing serves HTTPS, so a redirect to it would only break every
# request that did not come from localhost.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
